import { Router, type IRouter } from "express";
import PDFDocument from "pdfkit";
import path from "node:path";
import fs from "node:fs";

const router: IRouter = Router();

const BRAND_RED = "#CD2727";
const BRAND_DARK = "#373F41";
const BRAND_GREY = "#6B7280";
const LOGO_CANDIDATES = [
  path.resolve(process.cwd(), "../airpak-express/public/apps/airpak/img/logo.png"),
  path.resolve(process.cwd(), "../airpak-express/dist/public/apps/airpak/img/logo.png"),
  path.resolve(process.cwd(), "artifacts/airpak-express/public/apps/airpak/img/logo.png"),
];

function findLogo(): string | null {
  for (const p of LOGO_CANDIDATES) {
    if (fs.existsSync(p)) return p;
  }
  return null;
}

type DocType = "invoice" | "waybill" | "receipt" | "label";

interface DocData {
  type: DocType;
  number?: string;
  date?: string;
  sender?: { name?: string; address?: string; phone?: string; email?: string };
  recipient?: { name?: string; address?: string; phone?: string; email?: string };
  items?: Array<{ description?: string; qty?: number; unit?: string; price?: number }>;
  notes?: string;
  weight?: string;
  service?: string;
  paymentMethod?: string;
  trackingNumber?: string;
}

function fmt(n: number) {
  return n.toLocaleString("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function drawHeader(doc: PDFKit.PDFDocument, title: string, docNo: string, date: string) {
  const logo = findLogo();
  if (logo) {
    try {
      doc.image(logo, 40, 35, { fit: [110, 50] });
    } catch {
      // ignore
    }
  }
  doc.fillColor(BRAND_DARK).font("Helvetica-Bold").fontSize(11);
  doc.text("AIRPAK EXPRESS SDN BHD", 170, 40);
  doc.font("Helvetica").fontSize(8).fillColor(BRAND_GREY);
  doc.text("Domestic & International Courier  •  airpak-express.site", 170, 55);
  doc.text("Customer Hotline: 1-300-AIRPAK  •  support@airpak-express.site", 170, 67);

  doc.fillColor(BRAND_RED).font("Helvetica-Bold").fontSize(22).text(title, 400, 40, { width: 160, align: "right" });
  doc.fillColor(BRAND_DARK).font("Helvetica").fontSize(9);
  doc.text(`No: ${docNo}`, 400, 68, { width: 160, align: "right" });
  doc.text(`Date: ${date}`, 400, 81, { width: 160, align: "right" });

  doc.moveTo(40, 100).lineTo(555, 100).strokeColor(BRAND_RED).lineWidth(2).stroke();
}

function drawPartyBlock(doc: PDFKit.PDFDocument, label: string, party: DocData["sender"], x: number, y: number) {
  doc.font("Helvetica-Bold").fontSize(9).fillColor(BRAND_RED).text(label.toUpperCase(), x, y);
  doc.font("Helvetica-Bold").fontSize(11).fillColor(BRAND_DARK).text(party?.name || "—", x, y + 14);
  doc.font("Helvetica").fontSize(9).fillColor(BRAND_DARK);
  if (party?.address) doc.text(party.address, x, y + 30, { width: 240 });
  let cy = y + 30 + (party?.address ? Math.ceil((party.address.length / 40)) * 12 : 0) + 4;
  if (party?.phone) {
    doc.text(`Tel: ${party.phone}`, x, cy);
    cy += 12;
  }
  if (party?.email) doc.text(party.email, x, cy);
}

function drawFooter(doc: PDFKit.PDFDocument) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    doc.font("Helvetica").fontSize(7).fillColor(BRAND_GREY);
    doc.text(
      `Airpak Express  •  Generated ${new Date().toLocaleString("en-MY")}  •  Page ${i + 1} of ${range.count}`,
      40,
      770,
      { width: 515, align: "center" },
    );
    doc.text(
      "This document was auto-generated by Airpak Express. For queries, contact support@airpak-express.site.",
      40,
      782,
      { width: 515, align: "center" },
    );
  }
}

function drawInvoice(doc: PDFKit.PDFDocument, d: DocData) {
  drawHeader(doc, "INVOICE", d.number || "INV-0001", d.date || new Date().toLocaleDateString("en-MY"));
  drawPartyBlock(doc, "Bill From", d.sender, 40, 120);
  drawPartyBlock(doc, "Bill To", d.recipient, 310, 120);

  const tableTop = 250;
  doc.rect(40, tableTop, 515, 22).fill(BRAND_RED);
  doc.fillColor("#fff").font("Helvetica-Bold").fontSize(10);
  doc.text("Description", 50, tableTop + 6, { width: 270 });
  doc.text("Qty", 330, tableTop + 6, { width: 40, align: "right" });
  doc.text("Unit", 380, tableTop + 6, { width: 60, align: "right" });
  doc.text("Price (RM)", 450, tableTop + 6, { width: 60, align: "right" });
  doc.text("Total", 515, tableTop + 6, { width: 40, align: "right" });

  let y = tableTop + 28;
  let grand = 0;
  const items = d.items || [];
  doc.fillColor(BRAND_DARK).font("Helvetica").fontSize(10);
  for (const it of items) {
    const qty = Number(it.qty || 0);
    const price = Number(it.price || 0);
    const line = qty * price;
    grand += line;
    doc.text(it.description || "—", 50, y, { width: 270 });
    doc.text(String(qty), 330, y, { width: 40, align: "right" });
    doc.text(it.unit || "ea", 380, y, { width: 60, align: "right" });
    doc.text(fmt(price), 450, y, { width: 60, align: "right" });
    doc.text(fmt(line), 515, y, { width: 40, align: "right" });
    y += 20;
    doc.moveTo(40, y - 4).lineTo(555, y - 4).strokeColor("#eee").lineWidth(0.5).stroke();
  }

  y += 14;
  doc.font("Helvetica-Bold").fontSize(11).fillColor(BRAND_DARK);
  doc.text("TOTAL", 380, y, { width: 130, align: "right" });
  doc.fillColor(BRAND_RED).text(`RM ${fmt(grand)}`, 515, y, { width: 40, align: "right" });

  if (d.paymentMethod) {
    doc.fillColor(BRAND_GREY).font("Helvetica").fontSize(9).text(`Payment method: ${d.paymentMethod}`, 40, y + 30);
  }
  if (d.notes) {
    doc.fillColor(BRAND_DARK).font("Helvetica-Oblique").fontSize(9).text(`Notes: ${d.notes}`, 40, y + 50, { width: 515 });
  }
}

function drawWaybill(doc: PDFKit.PDFDocument, d: DocData) {
  drawHeader(doc, "AIR WAYBILL", d.number || d.trackingNumber || "AWB-0001", d.date || new Date().toLocaleDateString("en-MY"));
  drawPartyBlock(doc, "Shipper", d.sender, 40, 120);
  drawPartyBlock(doc, "Consignee", d.recipient, 310, 120);

  const boxTop = 260;
  doc.rect(40, boxTop, 515, 90).strokeColor(BRAND_RED).lineWidth(1).stroke();
  doc.font("Helvetica-Bold").fontSize(9).fillColor(BRAND_RED);
  doc.text("SERVICE", 50, boxTop + 10);
  doc.text("WEIGHT", 200, boxTop + 10);
  doc.text("TRACKING #", 350, boxTop + 10);
  doc.font("Helvetica").fontSize(12).fillColor(BRAND_DARK);
  doc.text(d.service || "Standard Express", 50, boxTop + 26, { width: 140 });
  doc.text(d.weight || "—", 200, boxTop + 26, { width: 140 });
  doc.text(d.trackingNumber || d.number || "—", 350, boxTop + 26, { width: 200 });

  doc.font("Helvetica-Bold").fontSize(9).fillColor(BRAND_RED).text("CONTENTS", 50, boxTop + 56);
  const contents = (d.items || []).map((i) => `${i.qty || 1} x ${i.description || ""}`).join(", ") || "—";
  doc.font("Helvetica").fontSize(10).fillColor(BRAND_DARK).text(contents, 50, boxTop + 70, { width: 500 });

  if (d.notes) {
    doc.font("Helvetica-Oblique").fontSize(9).fillColor(BRAND_DARK).text(`Handling: ${d.notes}`, 40, 380, { width: 515 });
  }

  doc.font("Helvetica").fontSize(8).fillColor(BRAND_GREY);
  doc.text("Shipper Signature: ____________________________", 40, 700);
  doc.text("Date: ______________", 350, 700);
  doc.text("Received by: ____________________________", 40, 730);
  doc.text("Date: ______________", 350, 730);
}

function drawReceipt(doc: PDFKit.PDFDocument, d: DocData) {
  drawHeader(doc, "RECEIPT", d.number || "RCP-0001", d.date || new Date().toLocaleDateString("en-MY"));
  drawPartyBlock(doc, "Received From", d.sender, 40, 120);

  const tableTop = 230;
  doc.rect(40, tableTop, 515, 22).fill(BRAND_RED);
  doc.fillColor("#fff").font("Helvetica-Bold").fontSize(10);
  doc.text("Description", 50, tableTop + 6, { width: 360 });
  doc.text("Amount (RM)", 415, tableTop + 6, { width: 130, align: "right" });

  let y = tableTop + 28;
  let grand = 0;
  doc.fillColor(BRAND_DARK).font("Helvetica").fontSize(10);
  for (const it of d.items || []) {
    const qty = Number(it.qty || 1);
    const price = Number(it.price || 0);
    const line = qty * price;
    grand += line;
    doc.text(`${it.description || "—"} ${qty > 1 ? `(x${qty})` : ""}`, 50, y, { width: 360 });
    doc.text(fmt(line), 415, y, { width: 130, align: "right" });
    y += 20;
  }
  y += 10;
  doc.font("Helvetica-Bold").fontSize(12).fillColor(BRAND_DARK).text("TOTAL PAID", 50, y);
  doc.fillColor(BRAND_RED).text(`RM ${fmt(grand)}`, 415, y, { width: 130, align: "right" });
  if (d.paymentMethod) {
    doc.fillColor(BRAND_GREY).font("Helvetica").fontSize(9).text(`Payment method: ${d.paymentMethod}`, 50, y + 25);
  }
  doc.fillColor(BRAND_DARK).font("Helvetica-Oblique").fontSize(10).text("Thank you for choosing Airpak Express.", 40, y + 60, { width: 515, align: "center" });
}

function drawLabel(doc: PDFKit.PDFDocument, d: DocData) {
  drawHeader(doc, "SHIPPING LABEL", d.number || d.trackingNumber || "LBL-0001", d.date || new Date().toLocaleDateString("en-MY"));

  doc.rect(40, 120, 515, 200).strokeColor(BRAND_RED).lineWidth(1).stroke();
  drawPartyBlock(doc, "From", d.sender, 60, 135);
  drawPartyBlock(doc, "To", d.recipient, 330, 135);

  doc.rect(40, 340, 515, 80).fill(BRAND_RED);
  doc.fillColor("#fff").font("Helvetica-Bold").fontSize(13).text("SERVICE", 60, 355);
  doc.font("Helvetica").fontSize(18).text(d.service || "STANDARD EXPRESS", 60, 372);
  doc.font("Helvetica-Bold").fontSize(13).text("WEIGHT", 380, 355);
  doc.font("Helvetica").fontSize(18).text(d.weight || "—", 380, 372);

  doc.fillColor(BRAND_DARK).font("Helvetica-Bold").fontSize(12).text("TRACKING #", 40, 440);
  doc.fillColor(BRAND_RED).font("Helvetica-Bold").fontSize(28).text(d.trackingNumber || d.number || "—", 40, 458);

  // simple barcode-ish strokes
  const code = d.trackingNumber || d.number || "AIRPAK";
  let bx = 40;
  doc.fillColor(BRAND_DARK);
  for (let i = 0; i < code.length * 6; i++) {
    const w = ((code.charCodeAt(i % code.length) + i) % 4) + 1;
    doc.rect(bx, 510, w, 50).fill(BRAND_DARK);
    bx += w + 2;
    if (bx > 540) break;
  }
  doc.fillColor(BRAND_GREY).font("Helvetica").fontSize(9).text(code, 40, 565, { width: 515, align: "center" });
  if (d.notes) {
    doc.fillColor(BRAND_DARK).font("Helvetica-Oblique").fontSize(10).text(`Handling: ${d.notes}`, 40, 600, { width: 515 });
  }
}

router.post("/documents/generate", (req, res): void => {
  try {
    const d = req.body as DocData;
    if (!d || !d.type) {
      res.status(400).json({ error: "type is required" });
      return;
    }

    const doc = new PDFDocument({ size: "A4", margin: 40, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => {
      const pdf = Buffer.concat(chunks);
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader(
        "Content-Disposition",
        `attachment; filename="airpak-${d.type}-${d.number || Date.now()}.pdf"`,
      );
      res.send(pdf);
    });

    if (d.type === "invoice") drawInvoice(doc, d);
    else if (d.type === "waybill") drawWaybill(doc, d);
    else if (d.type === "receipt") drawReceipt(doc, d);
    else if (d.type === "label") drawLabel(doc, d);
    else {
      doc.end();
      res.status(400).json({ error: `unknown document type: ${d.type}` });
      return;
    }

    drawFooter(doc);
    doc.end();
  } catch (err) {
    req.log?.error({ err }, "documents error");
    res.status(500).json({ error: "Failed to generate document" });
  }
});

export default router;
